/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3;

public class App {
    public static void main(String[] args) {
        Image img = new Image(2,2);
        img.crearBitmap();
        img.crearHexmap();
        img.crearPixmap();
        img.flipH();
        img.flipV();
    }
}
